export type LocationOption = {
  value: string;
  label: string;
};

export const CITY_OPTIONS = [
  "Chandigarh",
  "Mohali",
  "Zirakpur",
  "Panchkula",
  "Kharar",
  "New Chandigarh",
  "Derabassi",
  "Banur",
];

function sectors(values: Array<number | string>) {
  return values.map((value) => `Sector ${value}`);
}

function toOptions(values: string[]): LocationOption[] {
  return [...new Set(values)].map((value) => ({ value, label: value }));
}

export const CITY_SUB_LOCATIONS: Record<string, LocationOption[]> = {
  Chandigarh: toOptions([
    ...sectors([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "13 / Manimajra", 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 61, 63]),
    "Manimajra",
    "Modern Housing Complex",
    "Kishangarh",
    "Dhanas",
    "Maloya",
    "Mauli Jagran",
    "Industrial Area Phase 1",
    "Industrial Area Phase 2",
    "IT Park",
    "Raipur Khurd",
    "Raipur Kalan",
    "Other",
  ]),
  Mohali: toOptions([
    "Phase 1",
    "Phase 2",
    "Phase 3A",
    "Phase 3B1",
    "Phase 3B2",
    "Phase 4",
    "Phase 5",
    "Phase 6",
    "Phase 7",
    "Phase 8",
    "Phase 8B",
    "Phase 9",
    "Phase 10",
    "Phase 11",
    ...sectors([48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, "66A", 67, 68, 69, 70, 71, 73, 74, "74A", 75, 76, 77, 78, 79, 80, 81, 82, "82A", 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123]),
    "Aerocity",
    "Aerotropolis",
    "IT City",
    "Knowledge City",
    "Eco City",
    "JLPL",
    "Wave Estate",
    "Sunny Enclave",
    "TDI City",
    "Sohana",
    "Landran",
    "Kumbra",
    "Balongi",
    "Shahi Majra",
    "Mataur",
    "Phase 8 Industrial Area",
    "Industrial Area Phase 9",
    "Other",
  ]),
  Zirakpur: toOptions([
    "VIP Road",
    "Patiala Road",
    "Ambala Chandigarh Highway",
    "Dhakoli",
    "Peer Muchalla",
    "Gazipur",
    "Lohgarh",
    "Baltana",
    "Bhabat",
    "High Ground Road",
    "PR-7 Airport Road",
    "Singhpura",
    "Nagla Road",
    "Kishanpura",
    "Dayalpura",
    "Pabhat",
    "Utrathiya",
    "Motia Citi",
    "Sushma Chandigarh Grande Area",
    "Sushma Valencia Area",
    "Maya Garden Area",
    "Other",
  ]),
  Panchkula: toOptions([
    ...sectors([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, "12A", 14, 15, 16, 17, 18, 19, 20, 21, 23, 24, 25, 26, 27, 28, 30, 31, 32]),
    "Mansa Devi Complex",
    "MDC Sector 4",
    "MDC Sector 5",
    "MDC Sector 6",
    "Pinjore",
    "Kalka",
    "Old Panchkula",
    "Industrial Area Phase 1",
    "Industrial Area Phase 2",
    "Other",
  ]),
  Kharar: toOptions([
    "Kharar",
    "Sunny Enclave",
    ...sectors([115, 116, 117, 118, 119, 123]),
    "Gillco Valley",
    "Gillco Towers Area",
    "Shivalik City",
    "Shivalik City Sector 127",
    ...sectors([125, 126, 127, 128]),
    "Sector A",
    "Sector 124",
    "Kharar Landran Road",
    "Kharar Kurali Road",
    "Kharar Chandigarh Road",
    "Ranjit Nagar",
    "Dashmesh Nagar",
    "Guru Teg Bahadur Nagar",
    "Randhawa Road",
    "Nijjar Road",
    "Jandpur",
    "Khanpur",
    "Mundi Kharar",
    "Gopal Nagar",
    "Sante Majra",
    "Badala Road",
    "Other",
  ]),
  "New Chandigarh": toOptions([
    "Mullanpur",
    "Eco City 1",
    "Eco City 2",
    "Eco City 3",
    "Omaxe New Chandigarh",
    "DLF Hyde Park",
    "GMADA Eco City",
    "Medicity",
    "Education City",
    "Mullanpur Garibdass",
    "Sisal Estate Area",
    "Kurali-Siswan Road",
    "New Chandigarh Cricket Stadium Area",
    "PR-4 Area",
    "Other",
  ]),
  Derabassi: toOptions([
    "Dera Bassi",
    "Barwala Road",
    "Gulabgarh Road",
    "Haibatpur Road",
    "Mubarikpur",
    "Bhankharpur",
    "Issapur",
    "Saidpura",
    "Gholumajra",
    "Focal Point",
    "Industrial Area",
    "Chandigarh Ambala Highway",
    "ATS Golf Meadows Area",
    "SBP Housing Park Area",
    "Other",
  ]),
  Banur: toOptions([
    "Banur",
    "Banur Landran Road",
    "Banur Rajpura Road",
    "Banur Chandigarh Road",
    "Patiala Chandigarh Highway",
    "Chitkara University Area",
    "Jhansla",
    "Karala",
    "Manakpur",
    "Tangori",
    "Motemajra",
    "Ramgarh",
    "Kharar Banur Road",
    "Aerotropolis Extension Area",
    "Other",
  ]),
};
